MODEL: 
  #LOAD_PROPOSALS: True
  META_ARCHITECTURE: "GeneralizedRCNN"
  BACKBONE:
    NAME: "build_retinanet_resnet_fpn_backbone"
  RESNETS:
    OUT_FEATURES: ["res3", "res4", "res5"]
  FPN:
    IN_FEATURES: ["res3", "res4", "res5"]
  ANCHOR_GENERATOR:
    SIZES: !!python/object/apply:eval ["[[x] for x in [32, 64, 128, 256, 512 ]]"]
    NAME : "DenseBoxAnchorGenerator"
    OFFSET : 0.5
  PROPOSAL_GENERATOR:
    NAME: "FCOSRPN"
  RPN:
    IN_FEATURES: ["p3", "p4", "p5", "p6", "p7"]
    PRE_NMS_TOPK_TRAIN: 2000  # Per FPN level
    PRE_NMS_TOPK_TEST: 1000  # Per FPN level
    # Detectron1 uses 2000 proposals per-batch,
    # (See "modeling/rpn/rpn_outputs.py" for details of this legacy issue)
    # which is approximately 1000 proposals per-image since the default batch size for FPN is 2.
    POST_NMS_TOPK_TRAIN: 1000
    POST_NMS_TOPK_TEST: 1000
    BBOX_REG_LOSS_TYPE: 'giou'
  ROI_HEADS:
    NAME: "FCOSROIHeads"
    IN_FEATURES: ["p3", "p4", "p5", "p6", "p7"]
    #PROPOSAL_APPEND_GT: False
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_FC: 1
    POOLER_RESOLUTION: 7
    CLS_AGNOSTIC_BBOX_REG: True
    BBOX_REG_LOSS_TYPE: "giou"
    #TRAIN_ON_PRED_BOXES: True
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
  #PROPOSAL_FILES_TEST: ("detectron2://COCO-Detection/rpn_R_50_FPN_1x/137258492/coco_2017_val_box_proposals_ee0dad.pkl", )
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.02
  STEPS: (60000, 80000)
  MAX_ITER: 90000
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
VERSION: 2
