_BASE_: "../Base-FCOS.yaml"
MODEL:
  WEIGHTS: "output/FCOS_R_50_GN/R-50-GN.pkl"
  RESNETS:
    DEPTH: 50
    NORM: "GN"
  ANCHOR_GENERATOR:
    NAME : "DenseBoxAnchorGenerator"
  FPN:
    NORM: "GN"
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)


# This is similar to the setting used in Mask R-CNN paper, Appendix A
# But there are some differences, e.g., we did not initialize the output
# layer using the corresponding classes from COCO

OUTPUT_DIR: "output/COCO-Detection/FCOS_R_50_FPN_1x/"
