_BASE_: "../Base-FCOS.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
  ANCHOR_GENERATOR:
    NAME : "DenseBoxAnchorGenerator"
    OFFSET : 0.5
  FPN:
    REFINE_UPSAMPLE: True
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)


# This is similar to the setting used in Mask R-CNN paper, Appendix A
# But there are some differences, e.g., we did not initialize the output
# layer using the corresponding classes from COCO

OUTPUT_DIR: "output/COCO-Detection/FCOS_R_50_FPN_1x/"
