_BASE_: "../Base-RetinaNet.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
DATASETS:
  TRAIN: ("coco_2014_train",)
  TEST: ("coco_2014_train",)
OUTPUT_DIR: "output/COCO-Detection/retinanet_R_50_FPN_1x/"
