_BASE_: "../Base-IRNet.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
  IRNET:
    IN_FEATURES : ["res5"]
    NUM_CLASSES : 80
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)



# This is similar to the setting used in Mask R-CNN paper, Appendix A
# But there are some differences, e.g., we did not initialize the output
# layer using the corresponding classes from COCO

OUTPUT_DIR: "output/COCO-InstanceSegmentation/IRNet_R_50/"
